default: &default
  app_id: wx46c1198fe2a43173
  app_secret: 459f6ee22762db6455023a7ad52c3c20

development:
  <<: *default
  mch_id: <%= ENV["WEIXIN_MCH_ID"] %>
  pay_key: <%= ENV["WEIXIN_PAY_KEY"] %>
  order_template_id: QfYVgjqFRqy3iQx_UDDvgic0pUkGIkF2punq_XAI5zM
  middleware_token: f65a8604c16605b39535ee04
  middleware_secret: 2pNLlVETFlHyGlExgoH5h0daKIu_-iUv

test:
  <<: *default
  mch_id: <%= ENV["WEIXIN_MCH_ID"] %>
  pay_key: <%= ENV["WEIXIN_PAY_KEY"] %>

production:
  app_id: <%= ENV["WEIXIN_APP_ID"] %>
  app_secret: <%= ENV["WEIXIN_APP_SECRET"] %>
  mch_id: <%= ENV["WEIXIN_MCH_ID"] %>
  pay_key: <%= ENV["WEIXIN_PAY_KEY"] %>
  order_template_id: <%= ENV["ORDER_TEMPLATE_ID"] %>
  middleware_token: <%= ENV["WEIXIN_MIDDLEWARE_TOKEN"] %>
  middleware_secret: <%= ENV["WEIXIN_MIDDLEWARE_SECRET"] %>
